server:
  port: 8084
  
spring.application.name: cable
spring.cloud.config.discovery.enabled: true
spring.cloud.config.discovery.service-id: config

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/data4.sql;
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    
#DATABASE_TO_UPPER=false;
#DB_CLOSE_DELAY=-1;
#spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost