server:
  port: 8083
  
spring.application.name: fios
#spring.cloud.config.discovery.enabled: true
#spring.cloud.config.discovery.service-id: config

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost