server:
  port: 8086
  
spring.application.name: phone
#spring.cloud.config.discovery.enabled: true
#spring.cloud.config.discovery.service-id: config

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/data6.sql;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    
#DATABASE_TO_UPPER=false;
#DB_CLOSE_DELAY=-1;